"""empty message

Revision ID: 46c9c627b53
Revises: 5539743e7ba
Create Date: 2015-09-15 15:43:45.014400

"""

# revision identifiers, used by Alembic.
revision = '46c9c627b53'
down_revision = '5539743e7ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
